require 'spec_helper'

describe AthenaHealth::PatientInsurance do # cspell: disable
  subject { described_class.new(attributes) }

  let(:attributes) do
    {
      "insuredfirstname": 'KID',
      "insurancepolicyholdercity": 'SAN        FRANCISCO',
      "lastupdatedby": 'autoelig',
      "ircname": 'United Healthcare',
      "insurancephone": '(877)        842-3210',
      "insurancepolicyholderaddress1": '221B, BARKER STREET',
      "lastupdated": '02/26/2025',
      "relationshiptoinsured": 'Self',
      "eligibilitylastchecked": '02/26/2025',
      "insureddob": '01/01/2014',
      "insurancepolicyholder": 'KID        COSTA',
      "insurancepolicyholderstate": 'CA',
      "eligibilitystatus": 'Unverified',
      "insurancepolicyholdercountryiso3166": 'US',
      "created": '02/26/2025',
      "insuranceid": '26827',
      "insuredcity": 'SAN        FRANCISCO',
      "id": '26827',
      "insurancepolicyholdersex": 'M',
      "insurancepackagecity": 'ATLANTA',
      "insuranceplanname": 'UNITED        HEALTHCARE',
      "insuranceidnumber": '12345',
      "insuredzip": '12345',
      "insurancepayername": 'UHC',
      "insurancepackagepayerid": '87726',
      "eligibilityreason": 'Athena',
      "insurancepackagezip": '30374-0800',
      "insuranceplandisplayname": 'United        Healthcare',
      "insurancetype": 'Commercial',
      "insuredaddress": '221B, BARKER STREET',
      "insurancepolicyholdercountrycode": 'USA',
      "insurancepackageid": 982,
      "insuredlastname": 'COSTA',
      "insurancepackageaddress1": 'PO        BOX 740800',
      "insuredentitytypeid": 1,
      "insuredsex": 'M',
      "insurancepolicyholderdob": '01/01/2014',
      "insurancepolicyholderfirstname": 'KID',
      "sequencenumber": 1,
      "insuranceproducttype": 'OTHER',
      "insuredstate": 'CA',
      "ircid": 123,
      "createdby": 'p-lcosta2',
      "insurancepackagestate": 'GA',
      "relationshiptoinsuredid": 1,
      "insuredcountrycode": 'USA',
      "insurancepolicyholderlastname": 'COSTA',
      "insuredcountryiso3166": 'US',
      "insurancepolicyholderzip": '12345'
    }
  end

  it_behaves_like 'a model'

  it 'have proper attributes' do
    expect(subject).to have_attributes(
      "insuredfirstname": 'KID',
      "insurancepolicyholdercity": 'SAN        FRANCISCO',
      "lastupdatedby": 'autoelig',
      "ircname": 'United Healthcare',
      "insurancephone": '(877)        842-3210',
      "insurancepolicyholderaddress1": '221B, BARKER STREET',
      "lastupdated": '02/26/2025',
      "relationshiptoinsured": 'Self',
      "eligibilitylastchecked": '02/26/2025',
      "insureddob": '01/01/2014',
      "insurancepolicyholder": 'KID        COSTA',
      "insurancepolicyholderstate": 'CA',
      "eligibilitystatus": 'Unverified',
      "insurancepolicyholdercountryiso3166": 'US',
      "created": '02/26/2025',
      "insuranceid": '26827',
      "insuredcity": 'SAN        FRANCISCO',
      "id": '26827',
      "insurancepolicyholdersex": 'M',
      "insurancepackagecity": 'ATLANTA',
      "insuranceplanname": 'UNITED        HEALTHCARE',
      "insuranceidnumber": '12345',
      "insuredzip": '12345',
      "insurancepayername": 'UHC',
      "insurancepackagepayerid": '87726',
      "eligibilityreason": 'Athena',
      "insurancepackagezip": '30374-0800',
      "insuranceplandisplayname": 'United        Healthcare',
      "insurancetype": 'Commercial',
      "insuredaddress": '221B, BARKER STREET',
      "insurancepolicyholdercountrycode": 'USA',
      "insurancepackageid": 982,
      "insuredlastname": 'COSTA',
      "insurancepackageaddress1": 'PO        BOX 740800',
      "insuredentitytypeid": 1,
      "insuredsex": 'M',
      "insurancepolicyholderdob": '01/01/2014',
      "insurancepolicyholderfirstname": 'KID',
      "sequencenumber": 1,
      "insuranceproducttype": 'OTHER',
      "insuredstate": 'CA',
      "ircid": 123,
      "createdby": 'p-lcosta2',
      "insurancepackagestate": 'GA',
      "relationshiptoinsuredid": 1,
      "insuredcountrycode": 'USA',
      "insurancepolicyholderlastname": 'COSTA',
      "insuredcountryiso3166": 'US',
      "insurancepolicyholderzip": '12345'
    )
  end
end
